---
swagger: '2.0'
info:
  title: Upgrade Service Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

tags:
  - name: Channels
    description: Operations on release channels
  - name: Tiers
    description: Operations on network tiers

paths:
  /channels:
    get:
      summary: List all release channels
      tags:
      - Channels
      responses:
        '200':
          description: List of release channel IDs
          schema:
            type: array
            items:
              $ref: '#/definitions/channel_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Create a new release channel
      tags:
      - Channels
      parameters:
      - in: body
        name: channel
        description: The release channel to create
        required: true
        schema:
          $ref: '#/definitions/release_channel'
      responses:
        '201':
          description: ID of the created channel
          schema:
            $ref: '#/definitions/channel_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /channels/{channel_id}:
    get:
      summary: Retrieve release channel
      tags:
      - Channels
      parameters:
      - $ref: '#/parameters/channel_id'
      responses:
        '200':
          description: Release Channel
          schema:
            $ref: '#/definitions/release_channel'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Update a release channel
      tags:
      - Channels
      parameters:
      - $ref: '#/parameters/channel_id'
      - in: body
        name: channel
        description: Updated release channel
        required: true
        schema:
          $ref: '#/definitions/release_channel'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a release channel
      tags:
      - Channels
      parameters:
      - $ref: '#/parameters/channel_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/tiers:
    get:
      summary: List tiers in the network
      tags:
      - Tiers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: List of tiers in the network
          schema:
            type: array
            items:
              $ref: '#/definitions/tier_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new tier to the network
      tags:
      - Tiers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: tier
        description: Tier to add to the network
        required: true
        schema:
          $ref: '#/definitions/tier'
      responses:
        '201':
          description: ID of the created tier
          schema:
            $ref: '#/definitions/tier_id'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/tiers/{tier_id}:
    get:
      summary: Retrieve a tier
      tags:
      - Tiers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/tier_id'
      responses:
        '200':
          description: Network Tier
          schema:
            $ref: '#/definitions/tier'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify a tier
      tags:
      - Tiers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/tier_id'
      - in: body
        name: tier
        description: Updated tier
        required: true
        schema:
          $ref: '#/definitions/tier'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a tier
      tags:
      - Tiers
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/tier_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

parameters:
  channel_id:
    in: path
    name: channel_id
    description: Release Channel ID
    required: true
    type: string
  tier_id:
    in: path
    name: tier_id
    description: Tier ID
    required: true
    type: string

definitions:
  # Common definitions
  network_id:
    type: string
    minLength: 1
    example: NFHDZAQU8Pyw2N91nbNdGjk5e
  gateway_id:
    type: string
    minLength: 1
    example: NFHDZAQU8Pyw2N91nbNdGjk5e.22ffea10-7fc4-4427-975a-b9e4ce8f6f4d
  error:
    type: object
    required:
    - message
    properties:
      message:
        type: string
        example: Error string

  # Service definitions
  release_channel:
    type: object
    properties:
      name:
        type: string
      supported_versions:
        type: array
        items:
          type: string
  tier:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      version:
        type: string
      images:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            order:
              type: integer
  channel_id:
    type: string
    minLength: 1
    pattern: '^[a-zA-Z_][\da-zA-Z_]+$'
    example: stable
  tier_id:
    type: string
    minLength: 1
    pattern: '^[a-zA-Z_][\da-zA-Z_]+$'
    example: default