---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Add osquery repo key
  apt_key:
  args:
    keyserver: keyserver.ubuntu.com
    id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

- name: Add osquery repo
  apt_repository:
  args:
    mode: 664
    repo: "deb [arch=amd64] {{ osq_repo }}{{ osq_ver }} {{ osq_ver }} main"
    update_cache: yes

- name: Add osquery package
  apt: pkg=osquery state=present update_cache=no

- name: Copy osquery.flags file
  copy: src=osquery.flags dest=/etc/osquery/osquery.flags

- name: Retrieve API key from S3
  s3:
  args:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: "{{ osq_key_bucket }}"
    dest: /etc/osquery/api_token.key
    mode: get
    object: "{{ osq_key_object }}"
    region: "{{ osq_key_region }}"

- name: Start osquery
  command: osqueryctl start
